apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-rb
  namespace: sub-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: team-test
  namespace: team-test
#Grant the parent SA permission to modify resources in this namespace.
#✗ Kustomization reconciliation failed: HelmRelease/sub-team/podinfo dry-run failed, reason: Forbidden, error: helmreleases.helm.toolkit.fluxcd.io "podinfo" is forbidden: User "system:serviceaccount:team-test:team-test" cannot patch resource "helmreleases" in API group "helm.toolkit.fluxcd.io" in the namespace "sub-team"
